### ISSUE TITLE
Not show notification upload

### ISSUE THREAD

**Issue by tamhoangfit** [baole/snapbrite#101]
- thay xay ra khi internet cham

**Comment by baole** [comment]
Anh chưa hiểu trường hợp này lắm @tamhoangfit

**Comment by tamhoangfit** [comment]
kết lại, trường hợp này e thấy xảy ra khi post entry nhiều medias (đặc biệt là video & audio) lúc đó mặc dù click button post entry rồi mà chưa thấy show notification upload (taskservice upload có thể chưa chạy) chờ 3 -5 phút nó mới show notification upload
