### ISSUE TITLE
Admin Improvement

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#103]
More actions
- Send ActivationEmail
- Welcome email
- Welcome email (vi)
- Delete account

Email input
- get Info button (also show if account is not found or not activate
- 4 above action also included

@tamhoangfit em lam phia server de @damleanttek goi nhe.

**Comment by tamhoangfit** [comment]
da.

**Comment by damleanttek** [comment]
Đã có những function nào rồi anh @tamhoangfit

**Comment by damleanttek** [comment]
Trong Email input
Em nghĩ thêm bottom add vào.
khi click  vào buttom này sẽ add email đó vào first row của table và highline lên.
Lúc đó sẽ có đủ acctions cho email này trong table luôn ạ !!
A @baole ??

**Comment by tamhoangfit** [comment]
@damleanttek 
- welcomeEmail
- welcomeEmailVi
- deleteAccount

**Comment by damleanttek** [comment]
Done and Deployed in dev
