### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#109]
![image](https://cloud.githubusercontent.com/assets/1460168/11137272/b9f9802c-89e8-11e5-882d-4371b42651d8.png)

Few issues in editor
- Can not close editor (no button, no way to close without escape button (on phone))
- Location does not display
- Header: space between item is too large
- When no data: click on post don't do anything, should show a toast?
- Dialog: can we show just below the button?
- Select kid dialog
  + dont show scrollbar
  + should show close button
- No way to remove location

- Post on web, no notification on phone (I just test with the same account) ( @tamhoangfit  xem cai nay)

**Comment by damleanttek** [comment]
" Post on web, no notification on phone (I just test with the same account) ( @tamhoangfit xem cai nay)"
@tamhoangfit 
Test again thiss issues.

**Comment by tamhoangfit** [comment]
a test roi, co show notification on phone khi post tren web. doi luc gcm toi rat nhanh, thinh thoang 3-5 phut moi toi
