### ISSUE TITLE
tasker - turn down any request that is not from API module

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#11]

**Comment by LeHuynhTuan** [comment]
Add a secret key for checking if request is called from API

**Comment by baole** [comment]
@LeHuynhTuan maybe use follow params to be more secure

X-Appengine-Inbound-Appid
X-AppEngine-Cron: true

https://cloud.google.com/appengine/docs/python/requests#Python_Request_headers

**Comment by LeHuynhTuan** [comment]
Requests coming "from other App Engine applications" will include a header identifying the app making the request:

X-Appengine-Inbound-Appid

**Comment by LeHuynhTuan** [comment]
This header value is not set when call from API

**Comment by LeHuynhTuan** [comment]
forece add header value: 'X-Appengine-Inbound-Appid' when call from QueueApi. It look like secret key above
