### ISSUE TITLE
Card header

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#112]
![image](https://cloud.githubusercontent.com/assets/1460168/11137485/99fff04c-89ea-11e5-9c1a-fcb7a605ae92.png)
![image](https://cloud.githubusercontent.com/assets/1460168/11137491/b0bf3d4c-89ea-11e5-9a86-a9ff16da206c.png)
![image](https://cloud.githubusercontent.com/assets/1460168/11137513/f19e37b4-89ea-11e5-8708-558ccbd67635.png)

- Wrong ● unicode?
- Add a space between

**Comment by damleanttek** [comment]
Done
