### ISSUE TITLE
Unable start app after deleted Dummy Kid (Version code latest from SVN)

### ISSUE THREAD

**Issue by tamhoangfit** [baole/snapbrite#119]
W/System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.anttek.coral/com.anttek.coral.main.MainActivity}: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
11-19 14:46:33.039 5509-5509/com.anttek.coral W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
11-19 14:46:33.040 5509-5509/com.anttek.coral W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
11-19 14:46:33.040 5509-5509/com.anttek.coral W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:151)
11-19 14:46:33.040 5509-5509/com.anttek.coral W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
11-19 14:46:33.040 5509-5509/com.anttek.coral W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-19 14:46:33.040 5509-5509/com.anttek.coral W/System.err:     at android.os.Looper.loop(Looper.java:135)
11-19 14:46:33.040 5509-5509/com.anttek.coral W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
11-19 14:46:33.040 5509-5509/com.anttek.coral W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-19 14:46:33.041 5509-5509/com.anttek.coral W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
11-19 14:46:33.041 5509-5509/com.anttek.coral W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
11-19 14:46:33.041 5509-5509/com.anttek.coral W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
11-19 14:46:33.041 5509-5509/com.anttek.coral W/System.err: Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
11-19 14:46:33.041 5509-5509/com.anttek.coral W/System.err:     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
11-19 14:46:33.041 5509-5509/com.anttek.coral W/System.err:     at java.util.ArrayList.get(ArrayList.java:308)
11-19 14:46:33.041 5509-5509/com.anttek.coral W/System.err:     at com.anttek.coral.main.MomentsFragment.getBaby(MomentsFragment.java:215)
11-19 14:46:33.041 5509-5509/com.anttek.coral W/System.err:     at com.anttek.coral.main.MomentsFragment.loadData(MomentsFragment.java:103)
11-19 14:46:33.042 5509-5509/com.anttek.coral W/System.err:     at com.anttek.coral.main.MomentsFragment.onViewCreated(MomentsFragment.java:97)
11-19 14:46:33.042 5509-5509/com.anttek.coral W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1097)
11-19 14:46:33.042 5509-5509/com.anttek.coral W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
11-19 14:46:33.042 5509-5509/com.anttek.coral W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1241)
11-19 14:46:33.042 5509-5509/com.anttek.coral W/System.err:     at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2053)
11-19 14:46:33.042 5509-5509/com.anttek.coral W/System.err:     at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:165)
11-19 14:46:33.042 5509-5509/com.anttek.coral W/System.err:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:543)
11-19 14:46:33.043 5509-5509/com.anttek.coral W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
11-19 14:46:33.043 5509-5509/? W/System.err:     at android.app.Activity.performStart(Activity.java:6006)
11-19 14:46:33.043 5509-5509/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
11-19 14:46:33.043 5509-5509/? W/System.err: 	... 10 more
11-19 14:46:33.062 5509-5509/? I/Process: Sending signal. PID: 5509 SIG: 9

**Comment by sanglh** [comment]
Fixed.
