### ISSUE TITLE
Cannot show photo in PhotoFragment if media url is http://cdn.snapbrite.com/xxx

### ISSUE THREAD

**Issue by tamhoangfit** [baole/snapbrite#120]
- ngoai moments or timeline thi show duoc
- ben trong PhotoFragment, url bi add them suffix = s768 nen ko view duoc
(http://cdn.snapbrite.com/4886989748830208/062f0fe7-2e30-43f8-b39c-b44dd3204d47=s768

**Comment by sanglh** [comment]
Fixed
