### ISSUE TITLE
Moments & timeline

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#13]
Moments & Timeline: should display all kids tagged in an entry even some of them are “No Access” for account. This make sense when other account do actions on the entry (post comments, … mainly mentioned the rest kids), the account still got the case. 
Note: 
The account tap on avatar of kid which is “No Access” will do nothing (or go to page with more explain info such as “No Access page …”)
Account which do actions on the entry display account’s avatar and account’s name instead “Unknown”

@tamhoangfit add a new method to get kid avatar + name

**Comment by baole** [comment]
@tamhoangfit do you also implement on Android app?

**Comment by tamhoangfit** [comment]
yes, sorry. still impl on Android app

**Comment by sanglh** [comment]
Implemented
