### ISSUE TITLE
Event 43 - 51

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#23]
Do we implement these events?

    <string name="event_43">Get a trophy</string>
    <string name="event_44">Take schoolbus</string>
    <string name="event_45">Save money</string>
    <string name="event_46">First playground</string>
    <string name="event_47">Play sport game</string>
    <string name="event_48">Has first presents</string>
    <string name="event_49">Can read</string>
    <string name="event_50">Can write</string>
    <string name="event_51">Has first pets</string>

**Comment by NhuTang** [comment]
Yes. These events are for suggestions for child over 6 year-old

**Comment by hoa-le** [comment]
added
