### ISSUE TITLE
Ability to remove location info associated with photos

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#3]
I dont want to share EXIF tags of uploaded data which may be used to indentify my kids

**Comment by baole** [comment]
See more here:

http://stackoverflow.com/questions/10531544/write-geotag-jpegs-exif-data-in-android
http://developer.android.com/reference/android/media/ExifInterface.html

**Comment by baole** [comment]
trong advanced, then 1 option: title: Remove EXIF data
sum: remove locations and other  meta data of photos before upload to cloud
value: default OFF
neu ON len thi minh se remove EXIF khi copy vao app minh

**Comment by hoa-le** [comment]
done
