### ISSUE TITLE
Remove kid profile

### ISSUE THREAD

**Issue by NhuTang** [baole/snapbrite#35]
Removing kid profile has issues:
1. Story entry is deleted instead of only untagging removed kid (the entry has over 2 tagged kids)
2. Media entry is still showing removed kid (in Moments tab)

**Comment by baole** [comment]
- Delete kid
 - Un-tag deleted kid from entry
   - If no kid tagged for this entry, then delete entry

**Comment by baole** [comment]
Related code
- Timeline
- Entry viewer
- Authoring

@hoa-le review luon case nay nhe

**Comment by baole** [comment]
bug report
https://fabric.io/anttek2/android/apps/com.anttek.coral/issues/5630349cf5d3a7f76b21000c

**Comment by sanglh** [comment]
Implemented.

**Comment by hoa-le** [comment]
done
