### ISSUE TITLE
Remove kid without permission issue

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#37]
In kid profile, if not an admin then disable following actions
- Edit kid profile
- Sign in as kid
- Delete kid profile

**Comment by hoa-le** [comment]
Edit kid profile -> use to edit relationship -> can't disable

**Comment by hoa-le** [comment]
Delete kid profile - > remove relationship with kid
Sign in as kid -> has toast "You don't  have permission to do this"

**Comment by baole** [comment]
Delete kid profile - > remove relationship with kid
-> should change to "Unfollow" (Rename Disjoin to Unfollow)

Edit kid profile
- If Relationship is already set, then show Input dialog instead of "Dad/Mom..." popup

**Comment by hoa-le** [comment]
done, review it and this issue will close later

**Comment by baole** [comment]
edit relationship: neu da chon 1 lan roi thi show luon input dialog

**Comment by hoa-le** [comment]
done

**Comment by baole** [comment]
edit relationship: neu da chon 1 lan roi thi show luon input dialog
-> also apply in Kid profile editor

**Comment by hoa-le** [comment]
done
