### ISSUE TITLE
Web - big text is too dark in card

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#38]

**Comment by damleanttek** [comment]
just for story entry??

**Comment by baole** [comment]
![image](https://cloud.githubusercontent.com/assets/1460168/10778600/6e08e6e8-7d5a-11e5-96e8-6ac9a376ec72.png)

**Comment by damleanttek** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12420882/10779258/dfbfa316-7d60-11e5-80b8-b4fc0734f946.png)
How about that??

**Comment by longvu1234** [comment]
padding từ nội dung xuống comment count hơi nhiều

**Comment by damleanttek** [comment]
"padding từ nội dung xuống comment count hơi nhiều"
Fixed

**Comment by damleanttek** [comment]
plz review and i will close this issues.
@longvu1234
