### ISSUE TITLE
Web - layout

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#39]
Main
- +x more photos not showing
- More menu (click on ^ on card) shows a dialog with incorrect location
- Photo tab not showing all loaded photos

Kid detail
- entry's text not showing
- Growth chart: data card is bigger than other card
- Growth chart: reference data and data line color should be different

**Comment by baole** [comment]
![image](https://cloud.githubusercontent.com/assets/1460168/10778616/86bbeb40-7d5a-11e5-8492-df8388aef71c.png)

**Comment by damleanttek** [comment]
Growth chart: data card is bigger than other card: fixed

**Comment by baole** [comment]
Growth chart: Cm -> Weight standard

**Comment by damleanttek** [comment]
"Growth chart: Cm -> Weight standard" for layout??

**Comment by damleanttek** [comment]
entry's text not showing: fixed

**Comment by damleanttek** [comment]
More menu (click on ^ on card) shows a dialog with incorrect location
fixed

**Comment by damleanttek** [comment]
how about that? @baole 
![growth](https://cloud.githubusercontent.com/assets/12420882/10780404/a07f3b94-7d6f-11e5-87f4-adfc27b8d2f1.png)

**Comment by damleanttek** [comment]
+x more photos not showing: fixed

**Comment by damleanttek** [comment]
Done. waiting for review.

**Comment by damleanttek** [comment]
Anh @longvu1234 review dùm em.

**Comment by longvu1234** [comment]
trong tab Photo trên web , sao bấm vào hình này mà nó hiện review hình khác lên vậy?
