### ISSUE TITLE
Review Vietnamese translation all places in app

### ISSUE THREAD

**Issue by NhuTang** [baole/snapbrite#44]

**Comment by baole** [comment]
- Unfollow (Kid profile, unfollow trong truong hop ko phai admin) -> dang dich la "Xoa nhom"

**Comment by longvu1234** [comment]
cái câu mà bấm vào share link , lúc mà chưa có item hoặc chưa load ra , nó ghi là đường dẩn

**Comment by baole** [comment]
@longvu1234 noi o dau vay? screen nao? full sentence la gi?

**Comment by longvu1234** [comment]
trên timeline , chọn sharelink trong menu more , vào cái list share link (chia sẽ đường dẫn) , khi mà các item chưa load lên, đang sync về , hoặc ko có item nào , nò có 1 cái câu  báo .... , cái chữ dẫn ghi sai chính tả

**Comment by longvu1234** [comment]
![image](https://cloud.githubusercontent.com/assets/15354430/10781922/831c740e-7d7e-11e5-917f-364d15f2f660.png)
 nguyên câu sai chính tả

**Comment by baole** [comment]
Kid mình dịch là 'trẻ' hay 'bé' hay 'em bé'?

**Comment by NhuTang** [comment]
Em dang dich la "bé"

**Comment by NhuTang** [comment]
Done check and correct the translation. Also correct some English strings in Android code.
