### ISSUE TITLE
Bug when untagged

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#52]
Reproduce
- Create an entry with [indirect relationship](https://github.com/baole/snapbrite/wiki/Indirect-relationship). 
- Remove kid indirect relationship kid, then entry is not update on other devices

Example
- on A's device, create an entry with x, y, then sync
- B's device sees new entry with x, y
- on A's device, untag y, sync. 
- result: on B's device, show this entry
- expected: this entry (tag only x) should be remove from B's device

**Comment by baole** [comment]
This bug also happens when delete person.

**Comment by LeHuynhTuan** [comment]
Cái này e mới test lại thấy ok, test khoang 3 lần thì 2ok 1 lần bên device B ko update (co the la GCM cham). Xem database hay tren web thì vẫn đúng

**Comment by baole** [comment]
Trường hợp không update, em vào notification (Menu/notification) xem thử có update lại không Tuấn?

**Comment by LeHuynhTuan** [comment]
![p_20151029_113755](https://cloud.githubusercontent.com/assets/8609740/10810269/af67dde2-7e31-11e5-99c3-249eba64c251.jpg)

Truong hop doi ma ko co GCM thi ben device B thay nhu vay

**Comment by LeHuynhTuan** [comment]
![p_20151029_114117](https://cloud.githubusercontent.com/assets/8609740/10810304/187ab002-7e32-11e5-9b28-b4cd79e4510d.jpg)
den khi device B update dc entry thi notification cung update dc
