### ISSUE TITLE
Email - logo not show

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#54]
![image](https://cloud.githubusercontent.com/assets/1460168/10786325/2580598c-7d9c-11e5-823d-91b3a3fd38d5.png)

**Comment by LeHuynhTuan** [comment]
![image_not_shown](https://cloud.githubusercontent.com/assets/8609740/10808561/75f65852-7e1f-11e5-9aa2-2605ee07a78d.png)
![iamge_shown](https://cloud.githubusercontent.com/assets/8609740/10808562/7623319c-7e1f-11e5-8401-f6dc498873ee.png)

In my browser (Chrome), when i receive the mail -> I have to click on this link to show the logo
