### ISSUE TITLE
Email - should include plain link

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#55]
If user can not click on button (Confirm, cancel, activate), they can copy/paste link on browser to continue.

**Comment by LeHuynhTuan** [comment]
Applied for:
- Active account
- Confirm delete account
- Invitation no account
- Invitation account

**Comment by baole** [comment]
how about:
- Forget password?
- Reset password?

**Comment by LeHuynhTuan** [comment]
- dun have forget password email
- reset password: no link

**Comment by LeHuynhTuan** [comment]
Applied for invite using app
