### ISSUE TITLE
Delete account - not send GCM when delete baby

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#56]
Reproduce
- Sign in parent A
- Create kid x, share with parent B
- Delete A fro app's settings
- Re-signin A
- Open Gmail, confirm deletion
Result: A is still signed in, A is still shown in B
Expect
- A is signed out
- A is removed from B's device

@sanglh, @tamhoangfit

**Comment by baole** [comment]
Bug is even worst. Refresh family on B's device, but still show A

**Comment by baole** [comment]
Almost fixed. Need test

**Comment by tamhoangfit** [comment]
app: don't delete account when received GCM account  delete

**Comment by baole** [comment]
vi sao "app: don't delete account when received GCM account delete" @tamhoangfit ?

**Comment by sanglh** [comment]
Fixed.
