### ISSUE TITLE
Delete account - baby not delete

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#57]
Reproduce
- Sign in parent A
- Create kid x
- Invite parent B to join x as post + comment
- B accept invitation
- Delete parent A, confirm by email

Result: x is still in B's device
Expected: x is deleted since there is no admin on x

@sanglh review lai phia client
@tamhoangfit fix please

**Comment by baole** [comment]
Almost fixed. Need test

**Comment by LeHuynhTuan** [comment]
Test ok
