### ISSUE TITLE
Intro - bad alignment/padding

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#59]
![image](https://cloud.githubusercontent.com/assets/1460168/10789848/6d8048da-7db2-11e5-85a9-15b01dff2f2b.png)

@hoa-le xem lai

**Comment by longvu1234** [comment]
![axaxa](https://cloud.githubusercontent.com/assets/15354430/10809004/7a03b4a8-7e24-11e5-8a5d-8ba720694db7.PNG)

**Comment by baole** [comment]
@longvu1234  neu tren tablet Nexus 7 hoac Xoom thi sao?

**Comment by longvu1234** [comment]
vẫn vậy a, chỉ padding theo chiều dọc xuống , 2 bên thì mình canh giữa

**Comment by hoa-le** [comment]
padding sao ra dc 10%, 20%. phải căn theo, nói chung cái hình sẽ chính xác là 290dp còn lại chia theo % như em ?
Vậy trên cái xoom se bé lăm

**Comment by longvu1234** [comment]
![sdf](https://cloud.githubusercontent.com/assets/15354430/10809179/c4cb3054-7e26-11e5-85b7-fcb9f83eb253.PNG)
hoặc như vậy

**Comment by hoa-le** [comment]
theo a thì, từ hinh lên trên 10%, hình xuống chử 10%, chữ 5%, chử xuống indicator 10%,indicator xuống getting start 5%, getting start 10%, làm sao để hình nằm giữa, và mấy thăng còn lại cách đều nhau @longvu1234

**Comment by baole** [comment]
@hoa-le dung linear layout voi weight (total weight=100). 5% padding dung luon View(weight = 5) thay vi padding. Vay duoc ko?

**Comment by hoa-le** [comment]
được a, chia theo % thì mình sẽ làm % để phù hợp với all device, để long chốt design đã

**Comment by hoa-le** [comment]
![device-2015-10-29-113335](https://cloud.githubusercontent.com/assets/15263358/10810247/80315e9a-7e31-11e5-8c92-0b479cb5368d.png)
![device-2015-10-29-113546](https://cloud.githubusercontent.com/assets/15263358/10810249/8036d744-7e31-11e5-9657-46fef61d81b6.png)
![device-2015-10-29-113724](https://cloud.githubusercontent.com/assets/15263358/10810246/803160ac-7e31-11e5-8212-3884fa5f5644.png)
![device-2015-10-29-113739](https://cloud.githubusercontent.com/assets/15263358/10810248/80323310-7e31-11e5-8bda-528d9dff8267.png)
mọi người xem thử như vậy được chưa, Test trên nexus 4, 7

**Comment by hoa-le** [comment]
on Xoom 
![device-2015-10-29-121335](https://cloud.githubusercontent.com/assets/15263358/10810748/a87ef902-7e36-11e5-8ea9-527302e23b35.png)
![device-2015-10-29-121406](https://cloud.githubusercontent.com/assets/15263358/10810749/a8844448-7e36-11e5-84ba-fa5d175b51da.png)

**Comment by baole** [comment]
Hình cuối cùng lớn quá không? Có thể cho maxWidth của hình để nó nhỏ lại chút?

**Comment by hoa-le** [comment]
hình cuối là trên xoom 10inch, tại cái hình bo hết, qua mấy hình sau thì nó okie, máy lớn hình to nhìn mới đã :D, Cần thì nhỏ lại. em nghĩ sao @longvu1234
