### ISSUE TITLE
Incorrect padding in Invitation card

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#62]
![image](https://cloud.githubusercontent.com/assets/1460168/10808492/a11c0fdc-7e1e-11e5-978f-5b304149c192.png)

**Comment by longvu1234** [comment]
![timeline_new1](https://cloud.githubusercontent.com/assets/15354430/10808647/5c5a7e5e-7e20-11e5-82f4-b926ab700c64.jpg)

**Comment by longvu1234** [comment]
![timeline_new1](https://cloud.githubusercontent.com/assets/15354430/10808710/f610fcf8-7e20-11e5-89be-5800310b8e23.jpg)

**Comment by hoa-le** [comment]
fixed, code committed, review and will close issue later
