### ISSUE TITLE
Layout is not very nice

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#63]
![image](https://cloud.githubusercontent.com/assets/1460168/10808504/e287beb2-7e1e-11e5-93a0-c9e5f7970d19.png)

Also:
- click on back (actionbar) will not show popup
- relationship is optional

**Comment by longvu1234** [comment]
![new_invite](https://cloud.githubusercontent.com/assets/15354430/10810406/3db511a4-7e33-11e5-8ee8-7d729d7ae2ae.jpg)
