### ISSUE TITLE
Incorrect statusbar color

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#66]
![image](https://cloud.githubusercontent.com/assets/1460168/10810495/2c5bb10a-7e34-11e5-968f-7587409dcd60.png)

Reproduce
- Go to a kid detail
- Click on photo entry to open entry viewer
- press back to close entry viewer

Result: status bar color is gray
Expect: it should be colorPrimaryDark

**Comment by hoa-le** [comment]
fixed and committed
