### ISSUE TITLE
Compact mode

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#67]
Hide header of card on moment/timeline using TimelineAdapter.setCompactMode(). It's handy for small family (dad, mom, a kid)

- Add CheckboxPreference in Advanced settings, title: Compact mode, sum: Show less info on timeline, default=uncheck
- If this preference is not set then there is only one kid -> automatically turn this option ON, other wise turn it OFF. If set, do not change its value
- Effect on: new kid, getFamily() from cloud, where else?

**Comment by NhuTang** [comment]
Notice about layout (padding, margin); all entry type: story, event, media (with/without Title)

**Comment by NhuTang** [comment]
Hold this request.
