### ISSUE TITLE
Invitation reject bug

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#70]
- A invites B to join 5 kids
- B rejects all invitations
- A receives 5 rejections and shows correct notifications, but show wrong data in Parent detail (screenshot)

![image](https://cloud.githubusercontent.com/assets/1460168/10815427/8a396fa4-7e5e-11e5-9d13-5596c6c62c3c.png)

**Comment by hoa-le** [comment]
fixed and committed, đã test với reject 10 lời mời 1 lúc
