### ISSUE TITLE
Accept invitation from email, App does not update the invitee, status still "Pending"

### ISSUE THREAD

**Issue by NhuTang** [baole/snapbrite#71]
Reproduce:
- UserA invites B (email address, non-existing account) to share kid timeline
- B open email and click Reply Invitation
- B enter relationship and Accept
- UserA checks B profile, still "Pending"
- Try to exit app and reopen, still "Pending"

**Comment by tamhoangfit** [comment]
chi @NhuTang noi cai bug nay day. e sua lai roi replyInvitation neu chua co account return ve error require signup account

**Comment by tamhoangfit** [comment]
@damleanttek e fix ben web neu get error 107 thi show ex: require register account...
