### ISSUE TITLE
Share links - refinement

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#72]
- Person: only admin can create share link
- Entry: only admin or createdBy can create share link

**Comment by baole** [comment]
tien the, xu ly luon neu permission = comment only thi disable Photo wizard luon

**Comment by hoa-le** [comment]
Entry: only admin or createdBy can create share link -> entry được tag nhiều baby thì phải là admin của tất cả baby đó

**Comment by baole** [comment]
tac ca thi hop ly hon

**Comment by hoa-le** [comment]
cái đó sẽ sinh ra thêm 1 cái là cái menu sẽ ko có gì khi bấm vào, hồi trước còn có share link, giờ thì có gì hết, nếu chỉ là view, mà nếu để code ẩn trong adapter thì sẽ làm chậm adapter timeline

**Comment by hoa-le** [comment]
code committed
