### ISSUE TITLE
Sao xếp hình ko đẹp gì hết vậy? chừa ra 1 chỗ trống , cái zoom in zoom out sau khi refresh hay bị biến mất , xoay màn hình 1 hồi thì hết

### ISSUE THREAD

**Issue by longvu1234** [baole/snapbrite#73]
![screenshot_2015-10-29-18-14-31](https://cloud.githubusercontent.com/assets/15354430/10817044/ee3d335e-7e69-11e5-9bb6-bde17b5c12c2.png)
![screenshot_2015-10-29-18-20-41](https://cloud.githubusercontent.com/assets/15354430/10817045/ee648666-7e69-11e5-847e-437ddb1ccde1.png)

**Comment by baole** [comment]
Sao không có header (month/year)?

**Comment by hoa-le** [comment]
cái này ty a mượn máy xem tý long ơi

**Comment by longvu1234** [comment]
refresh cái nó bị vậy
Nexus bị , máy e cũng bị

**Comment by hoa-le** [comment]
fixed rồi nhé @longvu1234

**Comment by longvu1234** [comment]
test ra nữa tính sao ?

**Comment by hoa-le** [comment]
test ra nữa cho 10k

**Comment by longvu1234** [comment]
cái lỗ trống vẫn còn kìa

**Comment by hoa-le** [comment]
cái lỗ trống đó là tính toán, cái đó có thể phát triển sau :D, cái bug mất header trước đi e
