### ISSUE TITLE
GCM - set high priority for message that need instantly

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#76]
Ex.

- Invitation GCM
- ~~Delete xxx~~
- What else?

Ref https://developers.google.com/cloud-messaging/concept-options#setting-the-priority-of-a-message

**Comment by tamhoangfit** [comment]
Delete request ko set priority ah a @baole?

**Comment by baole** [comment]
Delete request ko can priority

**Comment by tamhoangfit** [comment]
vay invitation set nhung method nao a? hien tai e moi set cho inviteMember, accepted

**Comment by baole** [comment]
Tac ca invitation
