### ISSUE TITLE
Share multiple photos not working

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#83]
- Open File Explorer (I use Root Explorer)
- Select 3 photo files
- Click on More > Send
- Select Snapbrite

Result: nothing happened
Expect: 3 files will be inserted to authoring

**Comment by hoa-le** [comment]
Do Root Explorer ko có post Minetype lên, Log ra thầy intent ko có minetype, vào photo or File Explorer share thấy okie, có nên chỉnh lại bên Root Explorer, hay là dùng uri để lấy minetype bên Snap brite ?

**Comment by baole** [comment]
Sao Facebook van nhan duoc?

**Comment by hoa-le** [comment]
fixed and committed
