### ISSUE TITLE
Unspecified birthday

### ISSUE THREAD

**Issue by baole** [baole/snapbrite#9]
~~If birthday is unspecified, show "unknown birthday"~~

Assume birthday is "0" and format them

**Comment by baole** [comment]
Fixed

**Comment by baole** [comment]
When create kid profile, if user don't set birthday
-> set Jan 1, 2013 as default birthday

**Comment by hoa-le** [comment]
fixed

**Comment by baole** [comment]
In create kid profile, 
- set default birthday instead of "Optional".
- Move birthday on above Gender

**Comment by hoa-le** [comment]
done
