### ISSUE TITLE
GCSApi.uploadFile Request Timeout

### ISSUE THREAD

**Issue by tamhoangfit** [baole/snapbrite#98]

**Comment by baole** [comment]
timeout is set to 30 min for upload to GCS. @tamhoangfit  please test

**Comment by tamhoangfit** [comment]
cach nay e set thu roi a, test fail, bao loi 401 unauthorize

**Comment by baole** [comment]
Cách mới thế nào rồi?

**Comment by tamhoangfit** [comment]
oh sorry a. cach moi e thay work tot hon roi, nhung con gap 2 lan bi timeout xong retry upload lai ok
